#!/bin/bash

#==========================
# Health Monitor
#==========================

LOG_DIR="/var/log/syspilot"

DISK_THRESHOLD=80
MEM_THRESHOLD=80
CPU_THRESHOLD=80

#==========================
# Backup
#==========================

BACKUP_SOURCE=/home/kirti/Projects/SysPilot/test_data
BACKUP_DEST=/home/kirti/Projects/SysPilot/backups
BACKUP_KEEP=7

#==========================
# User Creation Related
#==========================

LOG_FILE="/home/kirti/Projects/SysPilot/logs/sysusers.log"
AUDIT_DIR="/home/kirti/Projects/SysPilot/audit"
DEFAULT_GROUP="Developers"

#==========================
# lOG Analyze
#==========================
REPORT_GENERATION_PATH="/var/log/syspilot"
SYSTEM_ERROR_PATH="/var/log/syslog"
SSH_ANALYSIS_PATH="/var/log/auth.log"

#==========================
# Service WatchDog 
#==========================
LOG_DIR="/var/log/syspilot"
LOG_FILES="$LOG_DIR/watchdog.log"
SERVICES=("ssh" "cron" "syspilot-demo.service")